# Generated by Django 5.1 on 2025-11-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='advance_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Advance Amount'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rent_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Rent Amount'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('mobile__isnull', False)), fields=('business', 'mobile'), name='unique_driver_mobile'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('alternate_mobile__isnull', False)), fields=('business', 'alternate_mobile'), name='unique_driver_alternate_mobile'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_party_name_business'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('gst_no__isnull', False)), fields=('gst_no',), name='unique_party_gst'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('mobile__isnull', False)), fields=('business', 'mobile'), name='unique_party_mobile'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('alternate_mobile__isnull', False)), fields=('business', 'alternate_mobile'), name='unique_party_alternate_mobile'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('vehicle_number',), name='unique_vehicle_number'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('business', 'vehicle_number'), name='unique_vehicle_number_business'),
        ),
    ]
