# Generated by Django 5.1 on 2025-11-14 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_bill_advance_amount_alter_bill_rent_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicleowner',
            unique_together={('business', 'owner_name', 'owner_mobile_number')},
        ),
    ]
