# Generated by Django 5.1 on 2025-11-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_alter_vehicleowner_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='party',
            name='unique_party_name_business',
        ),
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('business', 'name', 'mobile')},
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('mobile__isnull', False)), fields=('business', 'name', 'mobile'), name='unique_party_name_mobile_business'),
        ),
    ]
