# Generated by Django 5.1 on 2025-11-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_remove_party_unique_party_name_business_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='unique_vehicle_number',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
    ]
