# Generated by Django 5.1 on 2025-11-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_remove_vehicle_unique_vehicle_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='unique_vehicle_number_business',
        ),
    ]
