# Generated by Django 5.1 on 2025-11-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_remove_vehicle_unique_vehicle_number_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
