# Generated by Django 5.1 on 2025-11-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_alter_vehicle_vehicle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
