# Generated by Django 5.1 on 2025-11-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_alter_vehicle_vehicle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Custom Page',
                'verbose_name_plural': 'Custom Page',
                'managed': False,
            },
        ),
    ]
