# Generated by Django 5.1 on 2025-11-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_adminlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLink',
        ),
    ]
